# Generated by Django 4.2.4 on 2024-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rase_app', '0002_remove_user_about_user_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
