# Generated by Django 4.2.4 on 2024-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_station', models.CharField(max_length=100, verbose_name='ایستگاه مبدا')),
                ('destination_station', models.CharField(max_length=100, verbose_name='ایستگاه مقصد')),
                ('time_of_the_next_bus', models.CharField(max_length=100, verbose_name='زمان رسیدن اتوبوس بعدی')),
                ('start_time', models.CharField(max_length=100, verbose_name='ساعت شروع حرکت')),
                ('time_at_the_terminal', models.CharField(max_length=100, verbose_name='ساعت رسیدن به پایانه')),
            ],
            options={
                'verbose_name': 'time table',
                'verbose_name_plural': 'list time table',
            },
        ),
    ]
