# Generated by Django 4.2.4 on 2024-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rase_app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
