# Generated by Django 4.2.4 on 2024-01-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rase_app2', '0003_timetable_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='delete',
        ),
    ]
